routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\FGTSController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\INSSController;
use App\Http\Controllers\IRRFController;
use App\Http\Controllers\CargoController;
use App\Http\Controllers\DescontoController;
use App\Http\Controllers\AdicionalController;
use App\Http\Controllers\RelatorioController;
use App\Http\Controllers\DependenteController;
use App\Http\Controllers\FuncionarioController;
use App\Http\Controllers\FolhaDePagamentoController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

Route::resource('funcionarios', FuncionarioController::class);

Route::get('dependentes/{funcionario}', [DependenteController::class, 'index'])->name('dependentes.index');
Route::get('dependentes/{funcionario}/create', [DependenteController::class, 'create'])->name('dependentes.create');
Route::post('dependentes/{funcionario}', [DependenteController::class, 'store'])->name('dependentes.store');
Route::get('dependentes/{funcionario}/{dependente}', [DependenteController::class, 'show'])->name('dependente.show');
Route::get('dependentes/{funcionario}/{dependente}/edit', [DependenteController::class, 'edit'])->name('dependente.edit');
Route::delete('dependentes/{funcionario}/{dependente}', [DependenteController::class, 'destroy'])->name('dependente.destroy');

Route::get('adicional/{funcionario}', [AdicionalController::class, 'index'])->name('adicional.index');
Route::get('adicional/{funcionario}/create', [AdicionalController::class, 'create'])->name('adicionais.create');
Route::post('adicionais/{funcionario}', [AdicionalController::class, 'store'])->name('adicionais.store');
Route::get('adicional/{funcionario}/{adicional}', [AdicionalController::class, 'show'])->name('adicionais.show');
Route::delete('adicional/{funcionario}/{adicional}', [AdicionalController::class, 'destroy'])->name('adicionais.destroy');

Route::get('descontos/{funcionario}', [DescontoController::class, 'index'])->name('descontos.index');
Route::get('descontos/{funcionario}/create', [DescontoController::class, 'create'])->name('descontos.create');
Route::post('descontos/{funcionario}', [DescontoController::class, 'store'])->name('descontos.store');
Route::get('descontos/{funcionario}/{desconto}', [DescontoController::class, 'show'])->name('descontos.show');
Route::delete('descontos/{funcionario}/{desconto}', [DescontoController::class, 'destroy'])->name('descontos.destroy'); 

Route::get('folhaDePagamento/{funcionario}', [FolhaDePagamentoController::class, 'index'])->name('folhaDePagamento.index');
Route::get('folhaDePagamento/{funcionario}/create', [FolhaDePagamentoController::class, 'create'])->name('folhaDePagamento.create');
Route::post('folhaDePagamento/{funcionario}', [FolhaDePagamentoController::class, 'store'])->name('folhaDePagamento.store');
Route::get('folhaDePagamento/{funcionario}/{folhaId}', [FolhaDePagamentoController::class, 'show'])->name('folhaDePagamento.show');
Route::delete('folhaDePagamento/{funcionario}/{folha}', [FolhaDePagamentoController::class, 'destroy'])->name('folhaDePagamento.destroy');
Route::get('folhaDePagamento/{funcionario}/{folha}/print', [FolhaDePagamentoController::class, 'print'])->name('folhaDePagamento.print');

Route::resource('inss', INSSController::class);
Route::resource('irrf', IRRFController::class);
Route::resource('cargos', CargoController::class);
Route::resource('fgts', FGTSController::class);
Route::resource('relatorios', RelatorioController::class);

app/Http/Controllers/INSSController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreINSSRequest;
use App\Models\INSS;
use App\Services\INSSService;
use Illuminate\Contracts\View\View;

class INSSController extends Controller
{
    public function index(): View
    {
        return view("inss.index", [
            'inss' => INSS::orderBy('data_vigencia', 'desc')->paginate(10),
        ]);
    }

    public function create(): View
    {
        return view("inss.create");
    }

    public function store(StoreINSSRequest $request)
    {
        $data = $request->validated();        
        $data['percentual'] = (float) str_replace(',', '.', $data['percentual']);
        $data['valor_inicial'] = (float) str_replace(',', '.', $data['valor_inicial']);
        $data['valor_final'] = (float) str_replace(',', '.', $data['valor_final']);
        
        if (INSSService::verificarINSSCadastrado($data)) {
            return redirect()->back()->withErrors(['Já existe um INSS cadastrado com esses valores para a data de vigência.']);
        }
        
        INSS::create($data);
        return redirect()->route('inss.index');
    }

    public function show(string $id)
    {
        $inss = INSS::findOrFail($id);
        return view("inss.show", compact("inss"));
    }

    public function edit(string $id)
    {
        $inss = INSS::findOrFail($id);
        return view("inss.edit", compact("inss"));
    }

    public function update(StoreINSSRequest $request, string $id)
    {
        $data = $request->validated();
        $data['percentual'] = (float) str_replace(',', '.', $data['percentual']);
        $data['valor_inicial'] = (float) str_replace(',', '.', $data['valor_inicial']);
        $data['valor_final'] = (float) str_replace(',', '.', $data['valor_final']);
        
        $inss = INSS::findOrFail($id);
        $inss->update($data);
        return redirect()->route('inss.index');
    }

    public function destroy(string $id)
    {
        $inss = INSS::findOrFail($id);
        $inss->delete();
        return redirect()->route('inss.index');
    }
}

resources/views/inss/create.blade.php
@extends('layouts.cruds.forms', [
    'title' => 'Novo INSS',
])

@section('errors')
    <span>
        {{ $errors->first() }}
    </span>
@endsection

@section('form')
    <form action="{{ route('inss.store') }}" method="POST" class="grid max-w-screen-md gap-4 mx-auto sm:grid-cols-2"
        id="inss_create">

        @csrf

        @component('components.inputs.input', [
            'field' => 'percentual',
            'label' => 'Percentual',
            'required' => true,
            'type' => 'text',
            'instructions' => 'Sem o símbolo de porcentagem',
        ])
        
        @endcomponent

        @component('components.inputs.input', [
            'field' => 'valor_inicial',
            'label' => 'Valor Inicial',
            'required' => true,
            'type' => 'text',
        ])
        
        @endcomponent

        @component('components.inputs.input', [
            'field' => 'valor_final',
            'label' => 'Valor Final',
            'required' => true,
            'type' => 'text',
        ])
        
        @endcomponent

        @component('components.inputs.date', [
            'field' => 'data_vigencia',
            'label' => 'Data de Vigência',
            'required' => true,
        ])

        @endcomponent
        
        <div class="flex justify-center mt-2 sm:col-span-2">
            <button class="w-full btn btn-primary">
                Cadastrar
            </button>
        </div>
    </form>
@endsection

resources/views/inss/edit.blade.php
@extends('layouts.cruds.forms', [
    'title' => 'Editar INSS',
])

@section('errors')
    <span>
        {{ $errors->first() }}
    </span>
@endsection

@section('form')
    <form
        action="{{ route('inss.update', $inss->id) }}"
        class="grid max-w-screen-md gap-4 mx-auto sm:grid-cols-2"
        method="POST"
        id="inss_edit"
    >
        @method('PATCH')
        @csrf
        @component('components.inputs.input', [
            'field' => 'percentual',
            'label' => 'Percentual',
            'required' => true,
            'type' => 'text',
            'instructions' => 'Sem o símbolo de porcentagem',
            'value' => $inss->percentual,
        ])
            
        @endcomponent
        
        @component('components.inputs.input', [
            'field' => 'valor_inicial',
            'label' => 'Valor Inicial',
            'required' => true,
            'type' => 'text',
            'value' => $inss->valor_inicial,
        ])
            
        @endcomponent
        
        @component('components.inputs.input', [
            'field' => 'valor_final',
            'label' => 'Valor Final',
            'required' => true,
            'type' => 'text',
            'value' => $inss->valor_final,
        ])
            
        @endcomponent

        @component('components.inputs.date', [
            'field' => 'data_vigencia',
            'label' => 'Data de Vigência',
            'required' => true,
            'value' => $inss->data_vigencia,
        ])
        
        @endcomponent

        <div class="flex justify-center mt-2 sm:col-span-2">
            <button class="w-full btn btn-primary">
                Editar
            </button>
        </div>
    </form>
@endsection

resources/views/inss/index.blade.php
{{-- @dd($inss->links()) --}}
@extends('layouts.cruds.index', [
    'title' => 'INSS',
    'description' => 'Lista de INSS',
])

@section('buttons')
    @component('components.inputs.button', [
        'route' => route('inss.create'),
        'class' => 'bg-primary hover:bg-primary-focus',
    ])
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="#fff" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
        </svg>
    @endcomponent

    @component('components.inputs.button', [
        'route' => route('dashboard'),
        'class' => 'bg-secondary hover:bg-secondary-focus',   
    ])
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="#fff"
            class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round"
                d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
        </svg>
    @endcomponent
@endsection

@section('table')
        <div class="overflow-x-auto">
            <table class="table table-lg">
                <thead>
                    <tr>
                        <th>
                            Percentual
                        </th>
                        <th>
                            Valor Inicial
                        </th>
                        <th>
                            Valor Final
                        </th>
                        <th>
                            Data de Vigência
                        </th>
                        <th>
                            Ações
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($inss as $item)
                        <tr class="hover">
                            <td>
                                {{ number_format($item->percentual, 1) }}%
                            </td>
                            <td>
                                R${{ $item->valor_inicial }}
                            </td>
                            <td>
                                {{ $item->valor_final ? 'R$' . $item->valor_final : 'Sem limite' }}
                            </td>
                            <td>
                                {{ \Carbon\Carbon::parse($item->data_vigencia)->format('d/m/Y') }}
                            </td>
                            <td class="flex flex-col items-center justify-center">
                                <a href="{{ route('inss.show', $item->id) }}"
                                    class="text-xs text-slate-700 hover:text-gray-600">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                        stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                        <path stroke-linecap="round" stroke-linejoin="round"
                                            d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
                                        <path stroke-linecap="round" stroke-linejoin="round"
                                            d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                    </svg>
                                </a>
                                <a href="{{ route('inss.edit', $item->id) }}"
                                    class="text-xs text-slate-700 hover:text-gray-600">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                        stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                        <path stroke-linecap="round" stroke-linejoin="round"
                                            d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                                    </svg>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            
            <div class="mt-6">
                {{ $inss->links() }}
            </div>
        </div>
@endsection

resources/views/inss/show.blade.php
@extends('layouts.app')
@section('content')
    @include('layouts.components.navbar')

    @component('layouts.components.header', [
        'description' => $inss->percentual . '%',
        'title' => 'INSS',
    ])
        
    @endcomponent

    <div class="flex flex-row justify-end w-full px-4 mb-6 sm:px-8">
        <button class="btn btn-error btn-circle" onclick="my_modal_1.showModal()">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="#fff" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
            </svg>
        </button>

        <dialog id="my_modal_1" class="modal modal-error">
            <div class="modal-box">
                <h3 class="text-lg font-bold">
                    Tem certeza que deseja excluir o INSS?
                </h3>
                <form action="{{ route('inss.destroy', $inss->id) }}" method="POST" id="inss_destroy">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-red" type="submit">
                        Excluir
                    </button>
                    <a class="btn btn-gray" onclick="my_modal_1.close()">
                        Cancelar
                    </a>
                </form>
            </div>
        </dialog>
    </div>
@endsection