routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\FGTSController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\INSSController;
use App\Http\Controllers\IRRFController;
use App\Http\Controllers\CargoController;
use App\Http\Controllers\DescontoController;
use App\Http\Controllers\AdicionalController;
use App\Http\Controllers\RelatorioController;
use App\Http\Controllers\DependenteController;
use App\Http\Controllers\FuncionarioController;
use App\Http\Controllers\FolhaDePagamentoController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

Route::resource('funcionarios', FuncionarioController::class);

Route::get('dependentes/{funcionario}', [DependenteController::class, 'index'])->name('dependentes.index');
Route::get('dependentes/{funcionario}/create', [DependenteController::class, 'create'])->name('dependentes.create');
Route::post('dependentes/{funcionario}', [DependenteController::class, 'store'])->name('dependentes.store');
Route::get('dependentes/{funcionario}/{dependente}', [DependenteController::class, 'show'])->name('dependente.show');
Route::get('dependentes/{funcionario}/{dependente}/edit', [DependenteController::class, 'edit'])->name('dependente.edit');
Route::delete('dependentes/{funcionario}/{dependente}', [DependenteController::class, 'destroy'])->name('dependente.destroy');

Route::get('adicional/{funcionario}', [AdicionalController::class, 'index'])->name('adicional.index');
Route::get('adicional/{funcionario}/create', [AdicionalController::class, 'create'])->name('adicionais.create');
Route::post('adicionais/{funcionario}', [AdicionalController::class, 'store'])->name('adicionais.store');
Route::get('adicional/{funcionario}/{adicional}', [AdicionalController::class, 'show'])->name('adicionais.show');
Route::delete('adicional/{funcionario}/{adicional}', [AdicionalController::class, 'destroy'])->name('adicionais.destroy');

Route::get('descontos/{funcionario}', [DescontoController::class, 'index'])->name('descontos.index');
Route::get('descontos/{funcionario}/create', [DescontoController::class, 'create'])->name('descontos.create');
Route::post('descontos/{funcionario}', [DescontoController::class, 'store'])->name('descontos.store');
Route::get('descontos/{funcionario}/{desconto}', [DescontoController::class, 'show'])->name('descontos.show');
Route::delete('descontos/{funcionario}/{desconto}', [DescontoController::class, 'destroy'])->name('descontos.destroy'); 

Route::get('folhaDePagamento/{funcionario}', [FolhaDePagamentoController::class, 'index'])->name('folhaDePagamento.index');
Route::get('folhaDePagamento/{funcionario}/create', [FolhaDePagamentoController::class, 'create'])->name('folhaDePagamento.create');
Route::post('folhaDePagamento/{funcionario}', [FolhaDePagamentoController::class, 'store'])->name('folhaDePagamento.store');
Route::get('folhaDePagamento/{funcionario}/{folhaId}', [FolhaDePagamentoController::class, 'show'])->name('folhaDePagamento.show');
Route::delete('folhaDePagamento/{funcionario}/{folha}', [FolhaDePagamentoController::class, 'destroy'])->name('folhaDePagamento.destroy');
Route::get('folhaDePagamento/{funcionario}/{folha}/print', [FolhaDePagamentoController::class, 'print'])->name('folhaDePagamento.print');

Route::resource('inss', INSSController::class);
Route::resource('irrf', IRRFController::class);
Route::resource('cargos', CargoController::class);
Route::resource('fgts', FGTSController::class);
Route::resource('relatorios', RelatorioController::class);

app/Models/Funcionario.php
<?php

namespace App\Models;

use App\Models\Cargo;
use App\Models\Salario;
use App\Models\Desconto;
use App\Models\Adicional;
use App\Models\FuncionarioHasDependente;
use Illuminate\Database\Eloquent\Model; 
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Funcionario extends Model
{
    use HasFactory;

    protected $fillable = [
        'nome',
        'cpf',
        'carga_horaria',
        'data_admissao',
        'data_demissao',
        'cargo_id'
    ];

    public function cargo(): BelongsTo
    {
        return $this->belongsTo(Cargo::class);
    }

    public function funcionarioHasDependente(): HasMany
    {
        return $this->hasMany(FuncionarioHasDependente::class);
    }

    public function salario(): HasMany
    {
        return $this->hasMany(Salario::class);
    }

    public function folhaDePagamento(): HasMany
    {
        return $this->hasMany(FolhaDePagamento::class);
    }

    // one to many funcionario has desconto

    public function funcionarioHasDesconto(): HasMany
    {
        return $this->hasMany(Desconto::class);
    }

    // one to many funcionario has adicional

    public function funcionarioHasAdicional(): HasMany
    {
        return $this->hasMany(Adicional::class);
    }
}

app/Http/Controllers/FuncionarioController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreFuncionarioRequest;
use App\Models\Cargo;
use App\Models\Salario;
use App\Models\Funcionario;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\RedirectResponse;

class FuncionarioController extends Controller
{
    public function index(Request $request): View
    {
        $pesquisa = $request->get('cpf');

        if (!$pesquisa) {
            return view('funcionarios.index', [
                'funcionarios' => Funcionario::paginate(10),
            ]);
        }
    
        return view('funcionarios.index', [
            'funcionarios' => Funcionario::where('cpf', 'like', "%{$pesquisa}%")->paginate(10),
        ]);
    }

    public function create(): View
    {
        $cargos = Cargo::all();
        return view('funcionarios.create', compact('cargos'));
    }

    public function store(StoreFuncionarioRequest $request): RedirectResponse
    {
        $data = $request->validated();
        $data['salario'] = (float) str_replace(',', '.', $data['salario']);
        
        $funcionario = Funcionario::create($data);

        $this->cadastrarSalario($funcionario->id, $data['salario'], $data['data_admissao']);
        return redirect()->route('funcionarios.index');
    }

    public function cadastrarSalario($funcionario_id, $salario, $data_vigencia)
    {
        Salario::create([
            'valor' => $salario,
            'funcionario_id' => $funcionario_id,
            'data_vigencia' => $data_vigencia,
        ]);
    }

    public function show(Funcionario $funcionario)
    {
        $pages = [
            [
                'title' => 'Dependentes',
                'description' => 'Lista de dependentes do funcionário',
                'link' => route('dependentes.index', $funcionario),
            ],
            [
                'title' => 'Adicionais',
                'description' => 'Lista de adicionais do funcionário',
                'link' => route('adicional.index', $funcionario),
            ],
            [
                'title' => 'Descontos',
                'description' => 'Lista de descontos do funcionário',
                'link' => route('descontos.index', $funcionario),
            ],
            [
                'title' => 'Folhas de Pagamento',
                'description' => 'Lista de folhas de pagamento do funcionário',
                'link' => route('folhaDePagamento.index', $funcionario),
            ]
        ];

        return view('funcionarios.show', compact('funcionario', 'pages'));
    }

    public function edit(Funcionario $funcionario)
    {
        $cargos = Cargo::all();
        return view('funcionarios.edit', compact('funcionario', 'cargos'));
    }

    public function update(StoreFuncionarioRequest $request, Funcionario $funcionario)
    {
        $data = $request->validated();

        $data['salario'] = (float) str_replace(',', '.', $data['salario']);
        $data['salario'] = (float) str_replace(',', '.', $data['salario']);

        $funcionario->update([
            'nome' => $data['name'],
            'data_admissao' => $data['data_admissao'],
            'cpf' => $data['cpf'],
            'carga_horaria' => $data['carga_horaria'],
            'cargo_id' => $data['cargo_id'],
        ]);

        $this->cadastrarSalario($funcionario->id, $data['salario'], $data['data_admissao']);
        return redirect()->route('funcionarios.index');
    }

    public function destroy(Funcionario $funcionario)
    {
        $funcionario->delete();
        return redirect()->route('funcionarios.index');
    }
}

resources/views/funcionarios/create.blade.php
@extends('layouts.cruds.forms', [
    'title' => 'Novo Funcionário',
])

@section('errors')
    <span>
        {{ $errors->first() }}
    </span>
@endsection

@section('form')
    <form action="{{ route('funcionarios.store') }}" 
        method="POST" 
        class="grid max-w-screen-md gap-4 mx-auto sm:grid-cols-2"
        id="funcionario_create">
        @csrf
        @component('components.inputs.input', [
            'field' => 'name',
            'label' => 'Nome',
            'required' => true,
            'type' => 'text',
        ])
        @endcomponent


        @component('components.inputs.input', [
            'field' => 'cpf',
            'label' => 'CPF',
            'required' => true,
            'type' => 'text',
            'instructions' => 'Somente números',
        ])
        @endcomponent


        @component('components.inputs.input', [
            'field' => 'carga_horaria',
            'label' => 'Caraga Horária',
            'required' => true,
            'type' => 'text',
            
        ])
        @endcomponent


        @component('components.inputs.date', [
            'label' => 'Data de Admissão',
            'required' => true,
            'field' => 'data_admissao',
        ])
        @endcomponent


        @component('components.inputs.input', [
            'field' => 'salario',
            'label' => 'Salário',
            'required' => true,
            'type' => 'text',
        ])
        @endcomponent

        @component('components.inputs.select', [
            'label' => 'Cargo',
            'field' => 'cargo_id',
            'required' => true,
            'options' => $cargos,
        ])
        @endcomponent

        <div class="flex justify-center mt-2 sm:col-span-2">
            <button class="w-full btn btn-primary">
                Cadastrar
            </button>
        </div>
    </form>
@endsection

resources/views/funcionarios/edit.blade.php
@extends('layouts.cruds.forms', [
    'title' => 'Editar Funcionário',
])

@section('form')
    <form action="{{ route('funcionarios.update', $funcionario) }}" class="grid max-w-screen-md gap-4 mx-auto sm:grid-cols-2"
        method="POST" id="funcionario_edit">
        @method('PATCH')
        @csrf
        @component('components.inputs.input', [
            'field' => 'name',
            'label' => 'Nome',
            'required' => true,
            'type' => 'text',
            'value' => $funcionario->nome,
        ])
        @endcomponent

        @component('components.inputs.input', [
            'field' => 'cpf',
            'label' => 'CPF',
            'required' => true,
            'type' => 'text',
            'instructions' => 'Somente números',
            'value' => $funcionario->cpf,
        ])
        @endcomponent

        @component('components.inputs.input', [
            'field' => 'carga_horaria',
            'label' => 'Caraga Horária',
            'required' => true,
            'type' => 'text',
            'value' => $funcionario->carga_horaria,
        ])
        @endcomponent

        @component('components.inputs.date', [
            'label' => 'Data de Admissão',
            'required' => true,
            'field' => 'data_admissao',
            'value' => $funcionario->data_admissao,
        ])
        @endcomponent

        @component('components.inputs.input', [
            'field' => 'salario',
            'label' => 'Salário',
            'required' => true,
            'type' => 'text',
            'value' => $funcionario->salario->last()->valor ?? '',
        ])
        @endcomponent

        @component('components.inputs.select', [
            'label' => 'Cargo',
            'field' => 'cargo_id',
            'required' => true,
            'options' => $cargos,
            'value' => $funcionario->cargo_id,
        ])
        @endcomponent

    
        
        <div class="flex justify-center mt-2 sm:col-span-2">
            <button class="w-full btn btn-primary">
                Editar
            </button>
        </div>
    </form>
@endsection

resources/views/funcionarios/index.blade.php
@extends('layouts.cruds.index', [
    'title' => 'Funcionários',
    'description' => 'Lista de funcionários',
])

@section('buttons')
    <div class="flex flex-row items-center justify-between w-full">
        <form action="{{ route('funcionarios.index') }}" method="GET" class="flex items-center space-x-2">
            <fieldset>
                <label for="cpf" class="hidden">Pesquisar por CPF</label>
                <input type="search" name="cpf" placeholder="Pesquisar por CPF" class="input input-bordered">
            </fieldset>
            <button type="submit" class="btn btn-outline btn-circle btn-sm">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
                </svg>
            </button>
        </form>

        <div>
            @component('components.inputs.button', [
                'route' => route('funcionarios.create'),
                'class' => 'bg-primary hover:bg-primary-focus',
            ])
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="#fff" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                </svg>
            @endcomponent
            @component('components.inputs.button', [
                'route' => route('dashboard'),
                'class' => 'bg-secondary hover:bg-secondary-focus'
            ])
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="#fff"
                    class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round"
                        d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
                </svg>
            @endcomponent
        </div>
    </div>
@endsection

@section('table')
    @isset($funcionarios)
        <div class="overflow-x-auto">
            <table class="table table-lg">
                <thead>
                    <tr>
                        <th>
                            Nome
                        </th>
                        <th>
                            Cargo
                        </th>
                        <th>
                            CPF
                        </th>
                        <th>
                            Carga Horária
                        </th>
                        <th>
                            Salário
                        </th>
                        <th>
                            Data de Admissão
                        </th>
                        <th>
                            Data de Demissão
                        </th>
                        <th>
                            Ações
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($funcionarios as $funcionario)
                        <tr class="hover">
                            <th>
                                {{ $funcionario->nome }}
                            </th>
                            <td>
                                {{ $funcionario->cargo->nome ?? 'Sem cargo' }}
                            </td>
                            <td>
                                {{ $funcionario->cpf }}
                            </td>
                            <td>
                                {{ $funcionario->carga_horaria }} horas
                            </td>
                            <td>
                                R$ {{ $funcionario->salario()->latest('created_at')->first()->valor ?? '0,00' }}
                            </td>
                            <td>
                                {{ \Carbon\Carbon::parse($funcionario->data_admissao)->format('d/m/Y')}}
                            </td>
                            <td>
                                {{ \Carbon\Carbon::parse($funcionario->data_demissao)->format('d/m/Y') ?? 'Não demitido' }}
                            </td>
                            <td class="flex flex-col items-center justify-center">
                                <a 
                                    href="{{ route('funcionarios.show', $funcionario) }}"
                                    class="text-xs text-slate-700 hover:text-gray-600"
                                >
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                        stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                        <path stroke-linecap="round" stroke-linejoin="round"
                                            d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
                                        <path stroke-linecap="round" stroke-linejoin="round"
                                            d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                    </svg>
                                </a>
                                <a 
                                    href="{{ route('funcionarios.edit', $funcionario) }}"
                                    class="text-xs text-slate-700 hover:text-gray-600"
                                >
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                        stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                        <path stroke-linecap="round" stroke-linejoin="round"
                                            d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                                    </svg>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="mt-6">
                {{ $funcionarios->links() }}
            </div>
        </div>
    @endisset
@endsection

resources/views/funcionarios/show.blade.php
@extends('layouts.app')
@section('content')
    @include('layouts.components.navbar')

    @component('layouts.components.header', [
        'description' => $funcionario->nome,
        'title' => $funcionario->cargo->nome ?? 'Sem cargo',
    ])
    @endcomponent

    <div class="flex flex-row justify-end w-full px-4 mb-6 sm:px-8">
        @component('components.inputs.button', [
            'route' => route('funcionarios.index'),
            'class' => 'bg-neutral hover:bg-neutral-focus',
        ])
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="#fff" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M9 15L3 9m0 0l6-6M3 9h12a6 6 0 010 12h-3" />
            </svg>
        @endcomponent
        
        <button class="btn btn-error btn-circle hover:bg-error-focus" onclick="my_modal_1.showModal()">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="#fff" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
            </svg>
        </button>
        <dialog id="my_modal_1" class="modal modal-error">
            <div class="modal-box">
                <h3 class="text-lg font-bold">
                    Tem certeza que deseja excluir o funcionário?
                </h3>
                <form action="{{ route('funcionarios.destroy', $funcionario) }}" method="POST" id="funcionario_destroy">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-red" type="submit">
                        Excluir
                    </button>
                    <a class="btn btn-gray" onclick="my_modal_1.close()">
                        Cancelar
                    </a>
                </form>
            </div>
        </dialog>
    </div>

    <h2 class="text-2xl font-bold text-gray-700">
        Opções
    </h2>
    <section>
        <div class="grid w-full gap-4 p-10 md:grid-cols-3">
            @foreach ($pages as $page)
                @component('components.card', [
                    'title' => $page['title'],
                    'description' => $page['description'],
                    'link' => $page['link'],
                ])
                    
                @endcomponent
            @endforeach
        </div>
    </section>
@endsection